apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - "curl -s http://localhost:80/ || exit 1"
      initialDelaySeconds: 30
      periodSeconds: 30