apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-data-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nginx"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-data-volume
          mountPath: "/data/nginx"
  volumes:
    - name: nginx-data-volume
      persistentVolumeClaim:
        claimName: nginx-data-volume-claim